export {
  isRoleIn,
  isBusinessAdmin,
  getEffectiveRole,
  normalizeClientUser,
  getPostLoginPath,
  canViewExaminationList,
  canDiagnose,
  canPrescribe,
  canViewPayments,
  isBillPaid,
  canShowPaymentButtons,
  canShowPrintButton,
  canSendConfirmEmail,
} from './permissions';
